services:
  - type: web
    name: golden-bot
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: TOKEN
        value: ton_token_discord